name: Verify builder image

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker Image
      working-directory: ./.ci-dockerfiles/builder
      run: docker build . --file Dockerfile
