name: Verify builder image

on: pull_request

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build docker image
      working-directory: ./.ci-dockerfiles/builder
      run: docker build . --file Dockerfile
