name: Container

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build container
        working-directory: ./.ci-dockerfiles/builder
        runs:
          using: docker
          image: Dockerfile
