name: Container

on: [push]

jobs:
  container:
    name: Build container
    runs-on: ubuntu-latest
    uses: actions/checkout@v3
    working-directory: ./.ci-dockerfiles/builder
    runs:
      using: docker
      image: Dockerfile
