name: Build Container

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build Docker
      working-directory: ./.ci-dockerfiles/builder
      run: docker build . --file Dockerfile
