name: Build Container

on: [push]

jobs:
  container:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build docker container
      working-directory: ./.ci-dockerfiles/builder
      runs:
        using: docker
        image: Dockerfile
