name: Post sync agenda

on:
  schedule:
    - cron: "50 17 * * 2"

jobs:
  post-agenda:
    name: Post sync agenda to Zulip
    runs-on: ubuntu-latest
    container:
      image: ponylang/pony-sync-helper-ci-builder:latest
    steps:
      - uses: actions/checkout@v2
      - name: Today's date
        run: echo "DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      - name: Build sync-helper
        run: |
          corral fetch
          corral run -- ponyc -Dopenssl_0.9.0
      - name: Run sync-helper
        run: |
          echo 'AGENDA<<EOF' >> $GITHUB_ENV
          ./pony-sync-helper --org ponylang --github_token ${{PONY_SYNC_HELPER_GITHUB_TOKEN }}>> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          PONY_SYNC_HELPER_GITHUB_TOKEN: ${{ secrets.PONYLANG_MAIN_API_TOKEN }}
      - name: Post agenda
        uses: zulip/github-actions-zulip@35d7ad8e98444f894dcfe1d4e17332581d28ebeb
        with:
          api-key: ${{ secrets.ZULIP_SYNC_EVENT_API_KEY }}
          email: ${{ secrets.ZULIP_SYNC_EVENT_EMAIL }}
          organization-url: 'https://ponylang.zulipchat.com/'
          to: notifications
          type: stream
          topic: ${{ env.DATE }}
          content: ${{ env.AGENDA }}
